### ISSUE TITLE
The response being passed in isn't what always should be returned.

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/wallet-plugin-anchor#12]
https://github.com/wharfkit/wallet-plugin-anchor/blob/0420859856f444972de4bc5312f9ec7346405f97/src/index.ts#L226

This might be part of the problem with signatures being invalid. 

Anchor doesn't always return the same transaction it was sent, so just returning what was passed into the plugin is going to sometimes cause signature mismatches. 

What needs to be returned here is a resolved signing request based on the payload Anchor sends back.

https://github.com/greymass/anchor-link/blob/508599dd3fb3420b60ee2fa470bf60ce9ddca1c5/src/link.ts#L396-L400

**Comment by aaroncox** [comment]
This still doesn't work properly, I think it's because the resolved request still isn't enough (a problem to be solved with ESR). 

The request coming back from the wallet I believe is the request it signed, but not the request Wharf is expecting. 

This works:

```
            waitForCallback(callback)
                .then((callbackResponse) => {
                    ResolvedSigningRequest.fromPayload(callbackResponse, context.esrOptions)
                        .then((resolvedRequest) => {
                            SigningRequest.create(
                                {
                                    transaction: resolvedRequest.transaction,
                                },
                                context.esrOptions
                            ).then((newRequest) => {
                                cancelPrompt()
                                resolve({
                                    signatures: extractSignaturesFromCallback(callbackResponse),
                                    request: newRequest,
                                })
                            })
                        })
                        .catch((error) => {
                            reject(error)
                        })
                })
                .catch((error) => {
                    reject(error)
                })
```

This is because Wharf needs the full transaction (with tapos values) back and not just the partial request, which seems to be what Anchor is passing back and isn't being templated in to the default request (which I think is wrong).

The request is something like `actions: [...array of actions]`, and the request needs to be a full transaction.

I also wonder if instead of callback upon callback upon callback, if instead you could just use some `await` parameters to make the code a bit easier to follow along. That is probably just a matter of personal preference, but nesting callbacks can always get a bit hard to read.

**Comment by aaroncox** [comment]
I think the above also solves the issues with #10 - since the invalid signatures were being caused by these actually being different transactions (tapos).

**Comment by dafuga** [comment]
Oh awesome! Good job figuring that out!

**Comment by dafuga** [comment]
And yeah I agree that the callbacks are nested pretty deep at this point. I'll try using await statements like you suggested as it probably will be easier to follow in a case like this one.
