### ISSUE TITLE
Identity request creation

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/wallet-plugin-anchor#13]
https://github.com/wharfkit/wallet-plugin-anchor/blob/0420859856f444972de4bc5312f9ec7346405f97/src/anchor.ts#L53-L68

Is there a reason you're creating this manually, as opposed to using the function? 

I think you'd instead use `SigningRequest.identity()` and optionally pass in some of the parameters. This way it properly puts placeholders and stuff in. I think that's what this functions for 🤔 

https://github.com/greymass/eosio-signing-request/blob/6fc84b2355577d6461676bff417c76e4f6f2f5c3/src/signing-request.ts#L481-L485

**Comment by dafuga** [comment]
It looks like the the identity() method might not support multichain. I'll revert to using `createRequest` until we can fix that.
