### ISSUE TITLE
Using the `autocorrect` option in the web-ui causes permissions to be incorrectly set.

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/wallet-plugin-anchor#15]
I haven't looked into this, but when I use the autocorrect feature for the `wharftt21111`account on Jungle4 to purchase ram, the request that comes in defaults back to EOS and then uses the wrong account.

![wrongaccount](https://user-images.githubusercontent.com/677686/222938651-3b4601dd-419d-40c2-8e1d-77b0fad66807.gif)

**Comment by dafuga** [comment]
This is strange because when I login to non-EOS accounts using the other test transactions on the web UI, the correct chain and account are selected. I haven't looked into it, but is it possible that the autocorrect plugin is setting the esr chain to be EOS?

**Comment by aaroncox** [comment]
This should be resolved with the next release of the autocorrect plugin. 

It was recreating the ESR payload and losing all the data except the transaction in the process! 

Closing it here, since it's not a wallet plugin bug.
