### ISSUE TITLE
Bug preventing placeholder resolution from working

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/wallet-plugin-anchor#36]
bug in a bunch of our wallet plugins that was preventing placeholder resolution from working

When using action() on the contract kit how does it determine the current session?
My app allows account switching but the contract kit always sets the authorization to the same account

We can’t use the `resolved.request` value of a `ResolvedSigningRequest`, since it’s not resolved.

**Comment by aaroncox** [comment]
Resolved in 1.0.3.
